name:                require
version:             0.1.0.0
github:              "quytelda/require"
license:             BSD-3-Clause
author:              "Quytelda Kahja"
maintainer:          "quytelda@tamalin.org"
copyright:           "Copyright 2023 Quytelda Kahja"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quytelda/require#readme>

dependencies:
- aeson >= 2.1.2.1 && < 3
- base >= 4.7 && < 5
- servant >= 0.19.1 && < 0.21
- text >= 1.2.5 && < 3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  require-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - require

tests:
  require-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - require
